import { AppProvider } from '@/components/providers/app-provider'
import { cn } from '@/lib/utils'
import { SpeedInsights } from "@vercel/speed-insights/next"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      <meta charSet={"utf-8"} />
      </head>
      <body className={cn(
        inter.className,
        "bg-slate-200 dark:bg-slate-900 text-slate-900 dark:text-slate-100"
      )}>
        <AppProvider>
          {children}
        </AppProvider>
        <SpeedInsights/>
      </body>
    </html>
  )
}
