import { AppHeader } from '@/components/features/header'
import { AppRunningText } from '@/components/features/running-text'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'LPSK',
    description: 'Generated by create next app',
}

export default function Layout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className='w-full'>
            <AppHeader/>
            {children}
            <AppRunningText />
        </div>
    )
}
